### 5.3 Bag of Words (BoW) 

In [1]:
# count vectorizer iceriye aktar
from sklearn.feature_extraction.text import CountVectorizer

# veri seti olustur
documents = [
    "kedi bahcede",
    "kedi evde"]

# vectorizer tanimla 
vecto = CountVectorizer()

# metni sayisal vectorlere cevir 
X = vecto.fit_transform(documents)

# kelime kumesi olsuturma [bahcede, evde, kedi]
feature_names = vecto.get_feature_names_out()
print(feature_names)

# vector temsili 
print(X.toarray())


['bahcede' 'evde' 'kedi']
[[1 0 1]
 [0 1 1]]


### 5.4 BoW_imdb_datasets part 1

In [15]:
import pandas as pd 
from sklearn.feature_extraction.text import CountVectorizer
import re 
from collections import Counter

df = pd.read_csv("IMDB Dataset.csv")

# metin temizleme 
documents = df["review"]
labels =df["sentiment"] #posi or neg 

# metin temizleme 

def clean_text(text):

    # buyuk kucuk harf cevrimi
    text = text.lower()

    # rakamlari temizle
    text = re.sub(r"[^\w\s]", "", text)

    # kisa kelimeleri temizlenmesi
    text = " ".join([word for word in text.split() if len(word) > 2])

    # stop kelimeleri temizle
    stop_words = ['the', 'and', 'this', 'that', 'with','was','for', 'but', 'his']
    text = " ".join([word for word in text.split() if word not in stop_words])
    

    return text # temizlenms metin

# metinleri temizle 
cleaned_doc = [clean_text(doc) for doc in documents]

### 5.5 part 2 

In [16]:
# BoW 
vectorizer = CountVectorizer()

# metin -> sayisal hale getir 
X = vectorizer.fit_transform(cleaned_doc[:75])

# vektor temsili goster 
print(X.toarray())

df_bow = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())

# kelime frenkansini bul 
word_freq = X.sum(axis=0).A1
word_freq = dict(zip(vectorizer.get_feature_names_out(), word_freq))

# ilk 5 kelimeyi print et 
most_5 = Counter(word_freq).most_common(5)
print(most_5)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[('movie', 123), ('film', 98), ('not', 96), ('its', 83), ('are', 80)]


### 5.6 TF-IDF 

In [3]:
import pandas as pd 
import numpy as np 

from sklearn.feature_extraction.text import TfidfVectorizer

# ornek belge olustur
documents = [
    "kedi bahcede",
    "kedi evde",
    "kedi bahcede kedi",
    "kedi evde kedi",
]
# vektorizer tanimla
tfidf_vectorizer = TfidfVectorizer()

# meinleri sayisal hale cevir 
X = tfidf_vectorizer.fit_transform(documents)

# kelime kumesi incele
feature_names = tfidf_vectorizer.get_feature_names_out()

# vektor temsilini incele
print(f"vektor temsil:\n{X.toarray()}")

df_tfidf = pd.DataFrame(X.toarray(), columns=feature_names)

# ortalama tf idf degerlerine bakalım 
tf_idf = df_tfidf.mean(axis=0)

print(f"tf_idf:\n{tf_idf}")

vektor temsil:
[[0.83388421 0.         0.55193942]
 [0.         0.83388421 0.55193942]
 [0.60276058 0.         0.7979221 ]
 [0.         0.60276058 0.7979221 ]]
tf_idf:
bahcede    0.359161
evde       0.359161
kedi       0.674931
dtype: float64


### 5.8 Spam Datasets_Tf-idf

In [ ]:
import pandas as pd 
from sklearn.feature_extraction.text import TfidfVectorizer
import re
import nltk 
from nltk.corpus import stopwords
nltk.download("stopwords")

df = pd.read_csv("sms_spam.csv")

# veri temizleeme 
text = df["text"]
def clean_text(text):
        text = text.lower()
        text = re.sub(r"[^\w\s]", "", text)
        text = " ".join([word for word in text.split() if len(word) > 2])
        stop_words = set(stopwords.words("english"))
        text = " ".join([word for word in text.split() if word not in stop_words])
        return text # temizlenms metin
# metinleri temizle
cleaned_doc = [clean_text(doc) for doc in text]

# tfidf 
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(cleaned_doc)

# kelime kumesi incele
feature_names = vectorizer.get_feature_names_out()
tfidf_score = X.mean(axis=0).A1 # her kelimnin ortalama tf-idf degeri 

# tfidf skorlarını iceren bir df olsutur
df_tfidf = pd.DataFrame({"words": feature_names, "tfidf_score": tfidf_score})

# skorlarini sirala ve sonucları incele

df_tfidf_sorted = df_tfidf.sort_values(by="tfidf_score", ascending=False)
print(df_tfidf_sorted.head(10))


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mfurk\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


     words  tfidf_score
1870  call     0.019546
3631   get     0.013975
4236   ill     0.012983
2233  come     0.011805
2829  dont     0.011044
5003  ltgt     0.010865
3710  good     0.010063
4660  know     0.009999
3734   got     0.009841
4841  like     0.009737


### 5.9 N-Gram Model 

In [ ]:
# "bu bir ornek metindir"
    # unigram (n=1) 'Bu' , 'bir' , 'ornek' , 'metindir'
    # bigram (n=2) 'bu bir', 'bir ornek', 'ornek metindir'
    # trigram (n=3) 'bu bir ornek', 'bir ornek metindir'

    # ngram (n=4) 'bu bir ornek metindir'

# hem modelleme yapılabilir 
# hemde sınıflandırma yapılabilir 

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

# ornek metib 
documents = [
    "Bu çalısma NGram çalısmasıdır.",
    "Bu çalısma NGram çalısmasıdır. Bu bir ornek metindir.",
]

# unigram, bigram, trigram seklinde 3 farkli N degerine sahip ngram modeli 
vec_unigram = CountVectorizer(ngram_range=(1, 1))
vec_bigram = CountVectorizer(ngram_range=(2,2))
vec_trigram = CountVectorizer(ngram_range=(3,3))

# unigram 
X_unigram = vec_unigram.fit_transform(documents)
unigram_feature_names = vec_unigram.get_feature_names_out()

# bigram 
X_bigram = vec_bigram.fit_transform(documents)
bigram_features = vec_bigram.get_feature_names_out()

# trigram 
X_trigram = vec_trigram.fit_transform(documents)
bigram_features = vec_trigram.get_feature_names_out()

# sonucların incelenmesi
print("Unigram Feature Names: \n", unigram_feature_names )
print("Bigram Feature Names: \n", bigram_features)
print("Trigram Feature Names: \n", bigram_features)


Unigram Feature Names: 
 ['bir' 'bu' 'metindir' 'ngram' 'ornek' 'çalısma' 'çalısmasıdır']
Bigram Feature Names: 
 ['bir ornek metindir' 'bu bir ornek' 'bu çalısma ngram'
 'ngram çalısmasıdır bu' 'çalısma ngram çalısmasıdır'
 'çalısmasıdır bu bir']
Trigram Feature Names: 
 ['bir ornek metindir' 'bu bir ornek' 'bu çalısma ngram'
 'ngram çalısmasıdır bu' 'çalısma ngram çalısmasıdır'
 'çalısmasıdır bu bir']
